<?php
include '../class/commentaire.php';
/**
 * Created by PhpStorm.
 * User: stephane
 * Date: 22/02/15
 * Time: 12:04
 */

class commentaireTest extends PHPUnit_Framework_TestCase {

    public $com;

    public function test()
    {
        self::assertEquals("chela ouate",$this->com->getCommentaire());
        self::assertClassHasAttribute('id_commentaire','commentaire');
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->com = new commentaire("chela ouate");
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


}
